# 1、完成nan和inf的使用，掌握数组中nan值去除，替换为对应列的平均值

In [19]:
import numpy as np
t = np.arange(24, dtype=float).reshape(4,6)
t[1,3] = np.nan
t[2,4] = np.nan
t[2,2] = np.nan
print(t)
for i in range(t.shape[1]): #遍历ndarray
    t_col = t[:, i]
    nan_count = np.count_nonzero(t_col != t_col) #计算每列中的nan的数量
    if nan_count != 0: #如果本列中有nan
        t_col_num = t_col[t_col == t_col] #找出列中不是nan的数
        # print(t_col_num)
        t_col[np.isnan(t_col)] = np.mean(t_col_num) #将nan替换成平均数
print(t)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. nan 10. 11.]
 [12. 13. nan 15. nan 17.]
 [18. 19. 20. 21. 22. 23.]]
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. 13. 10. 11.]
 [12. 13. 10. 15. 12. 17.]
 [18. 19. 20. 21. 22. 23.]]


In [26]:
print(np.inf == np.inf)
print(np.inf)
print(np.inf > -np.inf)
print(np.nan + 1) # np.nan和任何数据运算的结果都是nan
print(np.nan + np.inf)

True
inf
True
nan
nan


# 2、np二维数组转置练习，轴滚动练习

In [38]:
t2 = np.arange(24, dtype=float).reshape(4,6)
print('原数组：')
print(t2)
print('转置数组：')
t3 = np.transpose(t2)
print(t3)
print('-'*50)
print('原数组：')
print(t2)
print('转置数组：')
print(t2.T) # 与transpose效果一致

原数组：
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
转置数组：
[[ 0.  6. 12. 18.]
 [ 1.  7. 13. 19.]
 [ 2.  8. 14. 20.]
 [ 3.  9. 15. 21.]
 [ 4. 10. 16. 22.]
 [ 5. 11. 17. 23.]]
--------------------------------------------------
原数组：
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
转置数组：
[[ 0.  6. 12. 18.]
 [ 1.  7. 13. 19.]
 [ 2.  8. 14. 20.]
 [ 3.  9. 15. 21.]
 [ 4. 10. 16. 22.]
 [ 5. 11. 17. 23.]]


In [46]:
t5 = np.arange(24).reshape(4,6)
print(t5)
rt5 = t5.swapaxes(1,0)
print(rt5)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]


In [57]:
t6 = np.arange(60).reshape(3, 4, 5)
print(t6.shape)
t7 = np.swapaxes(t6, 1, 2) #交换1、2轴
print(t7.shape)

(3, 4, 5)
(3, 5, 4)


In [63]:
a = np.ones((3, 4, 5, 6))
b = np.rollaxis(a, 1, 4) #轴1滚动到轴4之前
print(b.shape)
c = np.rollaxis(b, 3, 1) #轴3滚动到原先轴1的位置
print(c.shape)

(3, 5, 6, 4)
(3, 4, 5, 6)


# 3、练习series和df的索引操作,函数应用

In [72]:
import pandas as pd

# 生成一个Series
ser_obj = pd.Series(range(10, 20)) #默认索引是0-9
print(ser_obj)#打印输出会带有类型
print(ser_obj.index) #输出索引
print(ser_obj[0]) #输出索引为0的值

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64
RangeIndex(start=0, stop=10, step=1)
10


In [73]:
print(ser_obj * 2)  #元素级乘法
print(ser_obj > 15) #返回一个bool序列

0    20
1    22
2    24
3    26
4    28
5    30
6    32
7    34
8    36
9    38
dtype: int64
0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
8     True
9     True
dtype: bool


In [91]:
dict_data = {'A': 1,
             'B': pd.Timestamp('20190926'),
             'C': pd.Series(1, index=list(range(4)),dtype='float32'),
             'D': np.array([1,2,3,4],dtype='int32'),
             'E': ["Python","Java","C++","C"],
             'F': 'wangdao' } #数量不一致时自动补齐
df_obj2 = pd.DataFrame(dict_data)
print(df_obj2) 
print(df_obj2.index) #横轴和纵轴都有索引

   A          B    C  D       E        F
0  1 2019-09-26  1.0  1  Python  wangdao
1  1 2019-09-26  1.0  2    Java  wangdao
2  1 2019-09-26  1.0  3     C++  wangdao
3  1 2019-09-26  1.0  4       C  wangdao
Index([0, 1, 2, 3], dtype='int64')


In [79]:
ser_obj = pd.Series(range(5), index = list("abcde"))
print(ser_obj)
print(ser_obj.loc['b']) #索引名
print(ser_obj.iloc[2]) #位置索引

a    0
b    1
c    2
d    3
e    4
dtype: int64
1
2
b    1
c    2
dtype: int64
b    1
c    2
d    3
dtype: int64


In [80]:
# 切片索引
print(ser_obj.iloc[1:3])  #索引位置取数据，左闭右开
print(ser_obj.loc['b':'d'])  #记住索引名  左闭右闭

b    1
c    2
dtype: int64
b    1
c    2
d    3
dtype: int64


In [81]:
# 不连续索引
print(ser_obj.iloc[[0, 2, 4]])
print(ser_obj.loc[['a', 'e']])

a    0
c    2
e    4
dtype: int64
a    0
e    4
dtype: int64


In [83]:
# 布尔索引
print(ser_obj)
print(ser_obj > 2)

a    0
b    1
c    2
d    3
e    4
dtype: int64
a    False
b    False
c    False
d     True
e     True
dtype: bool


In [93]:
# DataFrame
df_obj = pd.DataFrame(np.random.randn(5,4),
                      columns = list('abcd'),
                      index=list('abcde'))
print(df_obj)
print('-'*50)
print(df_obj['a'])  #建议不用,拿的是列
print('-'*50)
print(df_obj.loc['a'])  #拿的是行
print('-'*50)

          a         b         c         d
a -0.203683 -0.204164  0.715020  1.171813
b -0.658924 -0.978993 -0.527293  2.285449
c  0.431893 -0.562826  1.487857  1.849048
d -0.345676  0.374863 -0.676084  0.879236
e  0.511436 -1.586973  0.770975  0.840487
--------------------------------------------------
a   -0.203683
b   -0.658924
c    0.431893
d   -0.345676
e    0.511436
Name: a, dtype: float64
--------------------------------------------------
a   -0.203683
b   -0.204164
c    0.715020
d    1.171813
Name: a, dtype: float64
--------------------------------------------------
          b         c         d
a -0.204164  0.715020  1.171813
b -0.978993 -0.527293  2.285449
c -0.562826  1.487857  1.849048
          b         d
a -0.204164  1.171813
c -0.562826  1.849048
          b
c -0.562826
-0.5628262502530105


In [94]:
# 第一个参数索引行，第二个参数是列,loc或者iloc效率高于直接用取下标的方式，前闭后闭
print(df_obj.loc['a':'c', 'b':'d']) #连续索引
print(df_obj.loc[['a','c'], ['b','d']]) #不连续索引
print(df_obj.loc[['c'],['b']]) #取一个值,返回的是DataFrame类型
print(df_obj.loc['c','b'])  #取一个值

          b         c         d
a -0.204164  0.715020  1.171813
b -0.978993 -0.527293  2.285449
c -0.562826  1.487857  1.849048
          b         d
a -0.204164  1.171813
c -0.562826  1.849048
          b
c -0.562826
-0.5628262502530105


In [95]:
s1 = pd.Series(range(10, 20), index = range(10))
s2 = pd.Series(range(20, 25), index = range(5))
# Series 对齐运算
print('s1+s2: ')
s3=s1+s2
print(s3)  #缺失数据默认是NaN  np.nan

s1+s2: 
0    30.0
1    32.0
2    34.0
3    36.0
4    38.0
5     NaN
6     NaN
7     NaN
8     NaN
9     NaN
dtype: float64


In [96]:
#两个长度不同的一维ndarray相加
a1 = np.array([1,2,3,4,5])
a2 = np.array([1]) # 长度为1
print(a2.shape)
print(a1+a2)

(1,)
[2 3 4 5 6]


In [97]:
print(s2)
s1

0    20
1    21
2    22
3    23
4    24
dtype: int64


0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64

In [98]:
print(np.isnan(s3[6]))
print('-'*50)
print(s2.add(s1, fill_value = 0))  #未对齐的数据将和填充值做运算
print(s2.sub(s1, fill_value = 0))

True
--------------------------------------------------
0    30.0
1    32.0
2    34.0
3    36.0
4    38.0
5    15.0
6    16.0
7    17.0
8    18.0
9    19.0
dtype: float64
0    10.0
1    10.0
2    10.0
3    10.0
4    10.0
5   -15.0
6   -16.0
7   -17.0
8   -18.0
9   -19.0
dtype: float64


In [99]:
# Numpy ufunc 函数，randn跟的是维数
df = pd.DataFrame(np.random.randn(5,4) - 1)
print(df)

print(np.abs(df)) #绝对值

          0         1         2         3
0 -2.005126  0.437498  1.622695 -2.447832
1 -1.198749 -1.220654 -1.481485 -2.335602
2 -0.884284 -0.679044 -0.042632 -0.375469
3 -0.443523  0.238447 -1.541976  0.201897
4 -1.416943 -1.698187 -1.620370 -1.871959
          0         1         2         3
0  2.005126  0.437498  1.622695  2.447832
1  1.198749  1.220654  1.481485  2.335602
2  0.884284  0.679044  0.042632  0.375469
3  0.443523  0.238447  1.541976  0.201897
4  1.416943  1.698187  1.620370  1.871959


In [100]:
#apply默认作用在列上,x是每一列,因为axis=0
print(df.apply(lambda x : x.max()))

0   -0.443523
1    0.437498
2    1.622695
3    0.201897
dtype: float64


# 4、练习处理缺失数据，统计与计算

In [128]:
df_data = pd.DataFrame([np.random.randn(3), [1., 2., np.nan],
                       [np.nan, 4., np.nan], [1., 2., 3.]])
print(df_data.head())

          0        1         2
0  1.310843 -0.45195  1.802445
1  1.000000  2.00000       NaN
2       NaN  4.00000       NaN
3  1.000000  2.00000  3.000000


In [102]:
#isnull来判断是否有空的数据
print(df_data.isnull())

       0      1      2
0  False  False  False
1  False  False   True
2   True  False   True
3  False  False  False


In [117]:
# 计算缺失率
print(df_data.isnull().sum()/len(df_data))

0    0.0
1    0.0
2    0.0
dtype: float64


In [122]:
#给零列的空值填为-100，按特征（按列）去填充
print(df_data.iloc[:,0].fillna(-100.))
df_data

0     -0.041889
1      1.000000
2   -100.000000
3      1.000000
Name: 0, dtype: float64


0         1         2
0 -0.041889  0.456095  0.100038
1  1.000000  2.000000  1.550019
2       NaN  4.000000  1.550019
3  1.000000  2.000000  3.000000

In [125]:
#依次拿到每一列
for i in df_data.columns:
    print(df_data.loc[:,i])

0   -0.041889
1    1.000000
2         NaN
3    1.000000
Name: 0, dtype: float64
0    0.456095
1    2.000000
2    4.000000
3    2.000000
Name: 1, dtype: float64
0    0.100038
1    1.550019
2    1.550019
3    3.000000
Name: 2, dtype: float64


In [132]:
df_data.iloc[:,0]=df_data.iloc[:,0].fillna(-100.) #第0列，用-100填充nan
df_data.iloc[:,2]=df_data.iloc[:,2].fillna(df_data.iloc[:,2].mean()) #用均值填充空值
df_data

0        1         2
0    1.310843 -0.45195  1.802445
1    1.000000  2.00000  2.401223
2 -100.000000  4.00000  2.401223
3    1.000000  2.00000  3.000000